// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCzBt-9HzTi5eVDKJ728Hha6Em1ebs4fEw',
    appId: '1:408279633368:web:812409e43b1e0a1c54f6ad',
    messagingSenderId: '408279633368',
    projectId: 'data-predictor-32a58',
    authDomain: 'data-predictor-32a58.firebaseapp.com',
    storageBucket: 'data-predictor-32a58.appspot.com',
    measurementId: 'G-XPXXV293SC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAvN0z4U70p2NnCKfnLuZPYc30lvPWE9iU',
    appId: '1:408279633368:android:7986f93a9921598e54f6ad',
    messagingSenderId: '408279633368',
    projectId: 'data-predictor-32a58',
    storageBucket: 'data-predictor-32a58.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDVX21t4q_cHw-tm9AaaVKWYTB74GZLF1c',
    appId: '1:408279633368:ios:f9df31373b2a4e3f54f6ad',
    messagingSenderId: '408279633368',
    projectId: 'data-predictor-32a58',
    storageBucket: 'data-predictor-32a58.appspot.com',
    iosBundleId: 'com.example.dataPredictor',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDVX21t4q_cHw-tm9AaaVKWYTB74GZLF1c',
    appId: '1:408279633368:ios:f9df31373b2a4e3f54f6ad',
    messagingSenderId: '408279633368',
    projectId: 'data-predictor-32a58',
    storageBucket: 'data-predictor-32a58.appspot.com',
    iosBundleId: 'com.example.dataPredictor',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCzBt-9HzTi5eVDKJ728Hha6Em1ebs4fEw',
    appId: '1:408279633368:web:812409e43b1e0a1c54f6ad',
    messagingSenderId: '408279633368',
    projectId: 'data-predictor-32a58',
    authDomain: 'data-predictor-32a58.firebaseapp.com',
    storageBucket: 'data-predictor-32a58.appspot.com',
    measurementId: 'G-XPXXV293SC',
  );

}